### ISSUE TITLE
Improve documentation w.r.t. logo ressoure

### ISSUE THREAD

**Issue by asr-enid** [eunid/netid-sdk-android#173]
As ressource are usually loaded via their numerical ids we should make it more clear that the SDK

1. Expects the logo ressource as a drawable asset in the main application package
2. Will search for it by its name

Readme and API surface (PermissionLayerConfig) should be more clear on that

**Comment by tbachmor-letsdev** [comment]
@asr-enid we could also rename the variable from 'logoId' to 'logoName' to make it more explicit, that the logo is referenced by its name (which is an id by itself, too) and not its resource id.
What's your opinion on this?
